// frontend/app/careers/page.tsx
import type { Metadata } from "next";

import { SimplePageShell } from "@/components/simple-page-shell";

export const metadata: Metadata = {
  title: "Careers and Driver Opportunities",
  description:
    "Explore courier, driver, and operations opportunities with INVO AURA Logistics across the UK.",
};

export default function CareersPage() {
  return (
    <SimplePageShell
      eyebrow="Careers"
      title="Drive with a dispatch team that values calm under pressure."
      description="We are building a premium logistics operation for drivers, dispatchers, and support teams who care about communication as much as delivery performance."
    >
      <article className="panel-glass p-6 sm:p-8">
        <h2 className="text-2xl font-semibold text-white">Why join INVO AURA?</h2>
        <div className="mt-5 grid gap-4 sm:grid-cols-3">
          {[
            "Dedicated business-focused routes and repeat client work.",
            "Operational visibility with a premium service culture.",
            "Growth opportunities across courier and support roles.",
          ].map((item) => (
            <div
              key={item}
              className="rounded-[1.4rem] border border-white/10 bg-white/5 p-4 text-sm leading-7 text-slate-300"
            >
              {item}
            </div>
          ))}
        </div>
      </article>
    </SimplePageShell>
  );
}

// frontend/vue-app/pages/careers.vue
<script setup lang="ts">
useSeoMeta({
  title: "Careers and Driver Opportunities",
  description:
    "Explore courier, driver, and operations opportunities with Invoaura Logistics.",
});
</script>

<template>
  <PublicPageShell
    eyebrow="Careers"
    title="Drive with a dispatch team that values calm under pressure."
    description="We are building a premium logistics operation for drivers, dispatchers, and support teams who care about communication as much as delivery performance."
  >
    <article class="surface-card p-6 sm:p-8">
      <h2 class="text-2xl font-semibold text-[var(--text-primary)]">
        Why join Invoaura?
      </h2>
      <div class="mt-5 grid gap-4 sm:grid-cols-3">
        <div
          v-for="item in [
            'Dedicated business-focused routes and repeat client work.',
            'Operational visibility with a premium service culture.',
            'Growth opportunities across courier and support roles.',
          ]"
          :key="item"
          class="rounded-[1.4rem] border border-[var(--border-color)] bg-black/[0.03] p-4 text-sm leading-7 text-secondary dark:bg-white/[0.03]"
        >
          {{ item }}
        </div>
      </div>
    </article>
  </PublicPageShell>
</template>
