// frontend/vue-app/components/crm/LeadsTable.vue
<script setup lang="ts">
import {
  ChevronLeft,
  ChevronRight,
  Download,
  Mail,
  MessageCircleMore,
  PhoneCall,
  FileUp,
} from "lucide-vue-next";
import type { LeadRecord } from "~/lib/crm";
import {
  formatCompactDate,
  formatCurrency,
  formatPhoneForWhatsApp,
} from "~/lib/crm";

defineProps<{
  leads: LeadRecord[];
  compact?: boolean;
  page?: number;
  totalPages?: number;
  emptyStateTitle?: string;
  emptyStateCopy?: string;
}>();

const emit = defineEmits<{
  open: [lead: LeadRecord];
  "page-change": [page: number];
  export: [];
  import: [];
}>();
</script>

<template>
  <div v-if="leads.length === 0" class="surface-card flex min-h-[320px] flex-col items-center justify-center p-8 text-center">
    <div class="flex h-16 w-16 items-center justify-center rounded-[24px] bg-[var(--accent-soft)] text-[var(--accent)]">
      <MessageCircleMore class="h-7 w-7" />
    </div>
    <h3 class="mt-6 text-2xl font-semibold text-[var(--text-primary)]">
      {{ emptyStateTitle ?? "No leads match this view" }}
    </h3>
    <p class="mt-3 max-w-md text-sm leading-7 text-muted">
      {{
        emptyStateCopy ??
        "Try a broader search, switch the date range, or reconnect your Firebase data source."
      }}
    </p>
  </div>

  <div v-else class="surface-card overflow-hidden">
    <div
      v-if="!compact"
      class="flex flex-col gap-3 border-b border-[var(--border-color)] p-5 sm:flex-row sm:items-center sm:justify-between"
    >
      <div>
        <p class="text-sm font-semibold text-[var(--text-primary)]">
          Leads inbox
        </p>
        <p class="mt-1 text-sm text-muted">
          Click a row to open the full lead drawer and update the record.
        </p>
      </div>
      <div class="flex items-center gap-3">
        <button
          type="button"
          class="inline-flex items-center gap-2 rounded-2xl bg-surface-container-high border border-outline-variant/30 px-4 py-3 text-sm font-semibold text-on-surface transition-all hover:-translate-y-0.5 hover:shadow-md hover:bg-surface-container-highest"
          @click="emit('import')"
        >
          <FileUp class="h-4 w-4" />
          Import
        </button>
        <button
          type="button"
          class="inline-flex items-center gap-2 rounded-2xl bg-[var(--accent)] px-4 py-3 text-sm font-semibold text-white transition-all hover:-translate-y-0.5 hover:shadow-lg hover:bg-[var(--accent-strong)]"
          @click="emit('export')"
        >
          <Download class="h-4 w-4" />
          Export CSV
        </button>
      </div>
    </div>

    <div class="hidden overflow-x-auto md:block">
      <table class="min-w-full text-left">
        <thead class="border-b border-[var(--border-color)] bg-black/[0.02] dark:bg-white/[0.02]">
          <tr class="text-xs uppercase tracking-[0.22em] text-muted">
            <th class="px-5 py-4 font-semibold">Name</th>
            <th class="px-5 py-4 font-semibold">Phone</th>
            <th class="px-5 py-4 font-semibold">Email</th>
            <th class="px-5 py-4 font-semibold">Pickup &amp; Delivery</th>
            <th class="px-5 py-4 font-semibold">Status</th>
            <th class="px-5 py-4 font-semibold">Created</th>
            <th v-if="!compact" class="px-5 py-4 font-semibold">Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="lead in leads"
            :key="lead.id"
            class="group cursor-pointer border-b border-[var(--border-color)] transition-all hover:bg-[var(--surface-accent)] dark:hover:bg-white/[0.04]"
            @click="emit('open', lead)"
          >
            <td class="px-5 py-4">
              <div>
                <p class="font-semibold text-[var(--text-primary)]">
                  {{ lead.name }}
                </p>
                <p class="mt-1 text-sm text-muted">{{ lead.company }}</p>
              </div>
            </td>
            <td class="px-5 py-4 text-sm text-secondary">{{ lead.phone }}</td>
            <td class="px-5 py-4 text-sm text-secondary">{{ lead.email }}</td>
            <td class="px-5 py-4">
              <p class="text-sm font-semibold text-[var(--text-primary)]">
                {{ lead.routeLabel }}
              </p>
              <p class="mt-1 text-sm text-muted">
                {{ lead.pickupAddress }} to {{ lead.deliveryAddress }}
              </p>
              <p
                v-if="lead.tags.length > 0"
                class="mt-2 text-xs uppercase tracking-[0.2em] text-muted"
              >
                {{ lead.tags.slice(0, 2).join(" • ") }}
              </p>
            </td>
            <td class="px-5 py-4">
              <div class="flex flex-col gap-2">
                <CrmStatusBadge :status="lead.status" />
                <CrmPriorityBadge :priority="lead.priority" />
              </div>
            </td>
            <td class="px-5 py-4">
              <p class="text-sm font-semibold text-[var(--text-primary)]">
                {{ formatCompactDate(lead.createdAt) }}
              </p>
              <p class="mt-1 text-xs text-muted">
                {{ formatCurrency(lead.estimatedValue) }}
              </p>
            </td>
            <td v-if="!compact" class="px-5 py-4">
              <div class="flex items-center gap-2" @click.stop>
                <a
                  :href="`tel:${formatPhoneForWhatsApp(lead.phone)}`"
                  class="rounded-2xl border border-[var(--border-color)] p-2 text-[var(--text-primary)] transition-all hover:-translate-y-0.5 hover:bg-[var(--accent)] hover:text-white hover:border-[var(--accent)] hover:shadow-lg"
                  :aria-label="`Call ${lead.name}`"
                >
                  <PhoneCall class="h-4 w-4" />
                </a>
                <a
                  :href="`https://wa.me/${formatPhoneForWhatsApp(lead.phone)}`"
                  target="_blank"
                  rel="noreferrer"
                  class="rounded-2xl border border-[var(--border-color)] p-2 text-[var(--text-primary)] transition-all hover:-translate-y-0.5 hover:bg-[var(--accent)] hover:text-white hover:border-[var(--accent)] hover:shadow-lg"
                  :aria-label="`Open WhatsApp for ${lead.name}`"
                >
                  <MessageCircleMore class="h-4 w-4" />
                </a>
                <a
                  :href="`mailto:${lead.email}`"
                  class="rounded-2xl border border-[var(--border-color)] p-2 text-[var(--text-primary)] transition-all hover:-translate-y-0.5 hover:bg-[var(--accent)] hover:text-white hover:border-[var(--accent)] hover:shadow-lg"
                  :aria-label="`Email ${lead.name}`"
                >
                  <Mail class="h-4 w-4" />
                </a>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="space-y-4 p-4 md:hidden">
      <button
        v-for="lead in leads"
        :key="lead.id"
        type="button"
        class="surface-card group hover-lift w-full rounded-[24px] p-4 text-left shadow-none transition-colors hover:border-[var(--accent-strong)] dark:hover:bg-white/[0.02]"
        @click="emit('open', lead)"
      >
        <div class="flex items-start justify-between gap-4">
          <div>
            <p class="text-base font-semibold text-[var(--text-primary)]">
              {{ lead.name }}
            </p>
            <p class="mt-1 text-sm text-muted">{{ lead.company }}</p>
          </div>
          <CrmStatusBadge :status="lead.status" />
        </div>
        <p class="mt-4 text-sm text-secondary">{{ lead.routeLabel }}</p>
        <div class="mt-3 flex flex-wrap items-center gap-2">
          <CrmPriorityBadge :priority="lead.priority" />
          <span
            v-for="tag in lead.tags.slice(0, 2)"
            :key="tag"
            class="muted-pill"
          >
            {{ tag }}
          </span>
        </div>
      </button>
    </div>

    <div
      v-if="!compact && (totalPages ?? 1) > 1"
      class="flex items-center justify-between border-t border-[var(--border-color)] px-5 py-4"
    >
      <p class="text-sm text-muted">
        Page {{ page ?? 1 }} of {{ totalPages ?? 1 }}
      </p>
      <div class="flex items-center gap-2">
        <button
          type="button"
          class="inline-flex items-center gap-2 rounded-2xl border border-[var(--border-color)] px-3 py-2 text-sm font-semibold text-[var(--text-primary)] disabled:cursor-not-allowed disabled:opacity-40"
          :disabled="(page ?? 1) === 1"
          @click="emit('page-change', (page ?? 1) - 1)"
        >
          <ChevronLeft class="h-4 w-4" />
          Previous
        </button>
        <button
          type="button"
          class="inline-flex items-center gap-2 rounded-2xl border border-[var(--border-color)] px-3 py-2 text-sm font-semibold text-[var(--text-primary)] disabled:cursor-not-allowed disabled:opacity-40"
          :disabled="(page ?? 1) === (totalPages ?? 1)"
          @click="emit('page-change', (page ?? 1) + 1)"
        >
          Next
          <ChevronRight class="h-4 w-4" />
        </button>
      </div>
    </div>
  </div>
</template>

// frontend/components/crm/LeadsTable.tsx
"use client";

import React, { useState } from "react";
import { Building2, MapPin, Phone, Globe, Mail, ChevronDown, ChevronUp, Bot, Sparkles } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

export interface Lead {
  id: string;
  company: string;
  location: string;
  phone: string;
  website: string;
  email: string;
  leadScore: number;
  aiSummary: string;
  draftEmail: string;
}

interface LeadsTableProps {
  leads: Lead[];
  onClose: () => void;
}

export function LeadsTable({ leads, onClose }: LeadsTableProps) {
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const getScoreColor = (score: number) => {
    if (score >= 80) return "text-emerald-500 bg-emerald-500/10 border-emerald-500/20";
    if (score >= 50) return "text-yellow-500 bg-yellow-500/10 border-yellow-500/20";
    return "text-red-500 bg-red-500/10 border-red-500/20";
  };

  return (
    <div className="flex flex-col h-full max-h-[85vh] w-full p-6 bg-white dark:bg-[#0c1322] rounded-3xl shadow-2xl border border-[var(--border)] overflow-hidden">
      <div className="flex justify-between items-center mb-6">
        <div>
          <h2 className="text-2xl font-black text-[var(--text-primary)] flex items-center gap-2">
             <Sparkles className="w-6 h-6 text-[var(--accent)]" /> Extracted Leads
          </h2>
          <p className="text-sm text-[var(--text-secondary)] mt-1">
             {leads.length} accounts processed and enriched via AI.
          </p>
        </div>
        <div className="flex gap-3">
          <button onClick={onClose} className="px-4 py-2 text-sm font-bold text-[var(--text-secondary)] hover:text-[var(--text-primary)] bg-[var(--bg-secondary)] hover:bg-[var(--border)] rounded-xl transition-all">
             Close
          </button>
          <button className="px-4 py-2 text-sm font-bold text-white bg-[var(--accent)] hover:bg-[var(--accent)]/90 shadow-lg shadow-[var(--accent)]/20 rounded-xl transition-all">
             Sync to CRM
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-auto rounded-2xl border border-[var(--border)] bg-[var(--surface-primary)]">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-[var(--bg-secondary)] sticky top-0 z-10 shadow-sm border-b border-[var(--border)]">
              <th className="p-4 text-xs font-bold text-[var(--text-secondary)] uppercase tracking-wider w-[25%]">Company</th>
              <th className="p-4 text-xs font-bold text-[var(--text-secondary)] uppercase tracking-wider w-[20%]">Location</th>
              <th className="p-4 text-xs font-bold text-[var(--text-secondary)] uppercase tracking-wider w-[25%]">Contact</th>
              <th className="p-4 text-xs font-bold text-[var(--text-secondary)] uppercase tracking-wider w-[15%]">AI Score</th>
              <th className="p-4 text-xs font-bold text-[var(--text-secondary)] uppercase tracking-wider w-[15%]">Details</th>
            </tr>
          </thead>
          <tbody>
            {leads.map((lead) => (
              <React.Fragment key={lead.id}>
                <tr className="border-b border-[var(--border)] hover:bg-[var(--bg-secondary)]/50 transition-colors group">
                  <td className="p-4">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-[var(--accent)]/10 text-[var(--accent)] flex items-center justify-center shrink-0">
                         <Building2 className="w-4 h-4" />
                      </div>
                      <span className="font-bold text-[var(--text-primary)] truncate">{lead.company}</span>
                    </div>
                  </td>
                  <td className="p-4">
                     <div className="flex items-center gap-2 text-sm text-[var(--text-secondary)] truncate">
                        <MapPin className="w-3.5 h-3.5" /> {lead.location}
                     </div>
                  </td>
                  <td className="p-4 space-y-1">
                     {lead.email && (
                       <div className="flex items-center gap-2 text-sm text-[var(--text-secondary)] truncate">
                         <Mail className="w-3.5 h-3.5" /> <a href={`mailto:${lead.email}`} className="hover:text-[var(--accent)] transition-colors">{lead.email}</a>
                       </div>
                     )}
                     {lead.phone && (
                       <div className="flex items-center gap-2 text-sm text-[var(--text-secondary)] truncate">
                         <Phone className="w-3.5 h-3.5" /> {lead.phone}
                       </div>
                     )}
                     {lead.website && (
                       <div className="flex items-center gap-2 text-sm text-[var(--text-secondary)] truncate">
                         <Globe className="w-3.5 h-3.5" /> <a href={lead.website} target="_blank" rel="noreferrer" className="hover:text-[var(--accent)] transition-colors">Website</a>
                       </div>
                     )}
                  </td>
                  <td className="p-4">
                     <div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md text-xs font-bold border ${getScoreColor(lead.leadScore)}`}>
                        <Bot className="w-3.5 h-3.5" />
                        {lead.leadScore} / 100
                     </div>
                  </td>
                  <td className="p-4">
                    <button 
                      onClick={() => setExpandedId(expandedId === lead.id ? null : lead.id)}
                      className="flex items-center gap-1.5 text-sm font-semibold text-[var(--accent)] hover:text-[var(--accent)]/80 transition-colors"
                    >
                       View AI Data {expandedId === lead.id ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                    </button>
                  </td>
                </tr>
                <AnimatePresence>
                  {expandedId === lead.id && (
                    <motion.tr 
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: "auto" }}
                      exit={{ opacity: 0, height: 0 }}
                      className="bg-[var(--bg-secondary)] overflow-hidden border-b border-[var(--border)]"
                    >
                      <td colSpan={5} className="p-0">
                         <div className="p-6 grid grid-cols-1 lg:grid-cols-2 gap-6">
                            <div className="space-y-2">
                               <h4 className="text-sm font-bold text-[var(--text-primary)] flex items-center gap-2">
                                 <Bot className="w-4 h-4 text-[var(--accent)]" /> AI Summary
                               </h4>
                               <p className="text-sm text-[var(--text-secondary)] leading-relaxed bg-[var(--surface-primary)] border border-[var(--border)] p-4 rounded-xl">
                                 {lead.aiSummary}
                               </p>
                            </div>
                            <div className="space-y-2">
                               <h4 className="text-sm font-bold text-[var(--text-primary)] flex items-center gap-2">
                                 <Mail className="w-4 h-4 text-emerald-500" /> Drafted Outreach
                               </h4>
                               <div className="text-sm text-[var(--text-secondary)] leading-relaxed bg-[var(--surface-primary)] border border-[var(--border)] p-4 rounded-xl whitespace-pre-line font-mono text-xs">
                                 {lead.draftEmail}
                               </div>
                            </div>
                         </div>
                      </td>
                    </motion.tr>
                  )}
                </AnimatePresence>
              </React.Fragment>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
